-- ============================================================
-- Seed Official GCG Decks
-- Uses uuid_generate_v5 for deterministic, idempotent IDs
-- Re-runnable: ON CONFLICT DO UPDATE
--
-- Auto-generated by: npm run sync-decks
-- Last synced: 2026-03-29
-- ============================================================

-- Fixed namespace UUID for official decks
-- Generated from: uuid_generate_v5(uuid_ns_url(), 'gundam-forge-official-decks')
DO $$
DECLARE
  ns uuid := '6ba7b811-9dad-11d1-80b4-00c04fd430c8'; -- UUID_NS_URL
  base_url text := 'https://gundam-forge.app/official-decks/';
  v_deck_id uuid;
BEGIN

  -- ─── deck-001: deck-001 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-001');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-001',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-001.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST01-001', 3, false),
    (v_deck_id, 'ST04-001', 3, false),
    (v_deck_id, 'ST01-002', 1, false),
    (v_deck_id, 'ST01-005', 2, false),
    (v_deck_id, 'ST04-005', 2, false),
    (v_deck_id, 'GD01-004', 1, false),
    (v_deck_id, 'GD01-005', 1, false),
    (v_deck_id, 'GD01-009', 1, false),
    (v_deck_id, 'GD01-011', 1, false),
    (v_deck_id, 'GD01-013', 1, false),
    (v_deck_id, 'GD01-018', 2, false),
    (v_deck_id, 'GD01-068', 1, false),
    (v_deck_id, 'GD01-077', 1, false),
    (v_deck_id, 'ST01-010', 2, false),
    (v_deck_id, 'ST04-010', 2, false),
    (v_deck_id, 'GD01-088', 1, false),
    (v_deck_id, 'GD01-089', 1, false),
    (v_deck_id, 'ST01-012', 1, false),
    (v_deck_id, 'ST01-013', 1, false),
    (v_deck_id, 'ST04-013', 1, false),
    (v_deck_id, 'GD01-100', 2, false),
    (v_deck_id, 'GD01-118', 1, false),
    (v_deck_id, 'ST01-015', 2, false),
    (v_deck_id, 'ST04-015', 1, false),
    (v_deck_id, 'GD01-124', 1, false);

  -- ─── deck-002: deck-002 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-002');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-002',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-002.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST02-001', 3, false),
    (v_deck_id, 'GD01-070', 3, false),
    (v_deck_id, 'ST02-002', 2, false),
    (v_deck_id, 'ST02-005', 1, false),
    (v_deck_id, 'ST03-008', 1, false),
    (v_deck_id, 'GD01-028', 2, false),
    (v_deck_id, 'GD01-030', 1, false),
    (v_deck_id, 'GD01-034', 1, false),
    (v_deck_id, 'GD01-040', 1, false),
    (v_deck_id, 'GD01-041', 2, false),
    (v_deck_id, 'GD01-075', 1, false),
    (v_deck_id, 'GD01-076', 1, false),
    (v_deck_id, 'ST01-011', 1, false),
    (v_deck_id, 'ST02-010', 2, false),
    (v_deck_id, 'GD01-091', 1, false),
    (v_deck_id, 'GD01-097', 1, false),
    (v_deck_id, 'ST02-012', 1, false),
    (v_deck_id, 'ST02-013', 1, false),
    (v_deck_id, 'GD01-107', 2, false),
    (v_deck_id, 'GD01-117', 1, false),
    (v_deck_id, 'GD01-118', 2, false),
    (v_deck_id, 'ST02-015', 2, false),
    (v_deck_id, 'ST04-015', 1, false);

  -- ─── deck-003: deck-003 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-003');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-003',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-003.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST01-001', 3, false),
    (v_deck_id, 'GD01-026', 3, false),
    (v_deck_id, 'ST01-002', 2, false),
    (v_deck_id, 'ST01-005', 2, false),
    (v_deck_id, 'ST02-001', 2, false),
    (v_deck_id, 'ST02-005', 1, false),
    (v_deck_id, 'ST03-007', 1, false),
    (v_deck_id, 'ST03-008', 2, false),
    (v_deck_id, 'GD01-004', 1, false),
    (v_deck_id, 'GD01-015', 1, false),
    (v_deck_id, 'GD01-016', 1, false),
    (v_deck_id, 'GD01-030', 1, false),
    (v_deck_id, 'GD01-031', 1, false),
    (v_deck_id, 'GD01-040', 1, false),
    (v_deck_id, 'ST01-010', 2, false),
    (v_deck_id, 'ST03-011', 2, false),
    (v_deck_id, 'ST02-010', 2, false),
    (v_deck_id, 'GD01-105', 1, false),
    (v_deck_id, 'ST01-013', 1, false),
    (v_deck_id, 'GD01-100', 2, false),
    (v_deck_id, 'GD01-099', 1, false),
    (v_deck_id, 'ST03-016', 1, false),
    (v_deck_id, 'ST01-015', 1, false);

  -- ─── deck-004: deck-004 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-004');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-004',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-004.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST01-010', 3, false),
    (v_deck_id, 'ST01-011', 3, false),
    (v_deck_id, 'ST01-014', 3, false),
    (v_deck_id, 'ST01-001', 2, false),
    (v_deck_id, 'ST01-002', 1, false),
    (v_deck_id, 'ST01-003', 1, false),
    (v_deck_id, 'ST01-004', 2, false),
    (v_deck_id, 'ST01-005', 2, false),
    (v_deck_id, 'ST01-006', 2, false),
    (v_deck_id, 'ST01-007', 1, false),
    (v_deck_id, 'ST01-009', 2, false),
    (v_deck_id, 'ST01-012', 1, false),
    (v_deck_id, 'ST01-015', 2, false);

  -- ─── deck-005: deck-005 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-005');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-005',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-005.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST02-001', 3, false),
    (v_deck_id, 'ST02-002', 4, false),
    (v_deck_id, 'ST02-006', 3, false),
    (v_deck_id, 'ST02-003', 1, false),
    (v_deck_id, 'ST02-005', 1, false),
    (v_deck_id, 'ST02-008', 2, false),
    (v_deck_id, 'ST02-009', 2, false),
    (v_deck_id, 'ST02-010', 2, false),
    (v_deck_id, 'ST02-011', 2, false),
    (v_deck_id, 'ST02-012', 1, false),
    (v_deck_id, 'ST02-014', 2, false),
    (v_deck_id, 'ST02-016', 1, false),
    (v_deck_id, 'ST02-015', 1, false);

  -- ─── deck-006: deck-006 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-006');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-006',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-006.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST03-001', 3, false),
    (v_deck_id, 'ST03-006', 3, false),
    (v_deck_id, 'ST03-013', 3, false),
    (v_deck_id, 'ST03-002', 1, false),
    (v_deck_id, 'ST03-003', 1, false),
    (v_deck_id, 'ST03-004', 2, false),
    (v_deck_id, 'ST03-007', 2, false),
    (v_deck_id, 'ST03-008', 2, false),
    (v_deck_id, 'ST03-009', 2, false),
    (v_deck_id, 'ST03-010', 2, false),
    (v_deck_id, 'ST03-011', 1, false),
    (v_deck_id, 'ST03-014', 1, false),
    (v_deck_id, 'ST03-015', 1, false);

  -- ─── deck-007: deck-007 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-007');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-007',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-007.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST04-006', 3, false),
    (v_deck_id, 'ST04-001', 3, false),
    (v_deck_id, 'ST04-012', 3, false),
    (v_deck_id, 'ST04-002', 2, false),
    (v_deck_id, 'ST04-003', 1, false),
    (v_deck_id, 'ST04-004', 1, false),
    (v_deck_id, 'ST04-005', 2, false),
    (v_deck_id, 'ST04-007', 2, false),
    (v_deck_id, 'ST04-008', 1, false),
    (v_deck_id, 'ST04-010', 1, false),
    (v_deck_id, 'ST04-011', 2, false),
    (v_deck_id, 'ST04-013', 2, false),
    (v_deck_id, 'ST04-015', 2, false);

  -- ─── deck-008: deck-008 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-008');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-008',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-008.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST04-001', 3, false),
    (v_deck_id, 'ST04-002', 1, false),
    (v_deck_id, 'ST04-010', 2, false),
    (v_deck_id, 'GD01-004', 2, false),
    (v_deck_id, 'GD01-065', 2, false),
    (v_deck_id, 'GD01-066', 2, false),
    (v_deck_id, 'GD01-067', 2, false),
    (v_deck_id, 'GD01-086', 1, false),
    (v_deck_id, 'GD01-100', 1, false),
    (v_deck_id, 'GD01-118', 1, false),
    (v_deck_id, 'ST01-009', 2, false),
    (v_deck_id, 'ST01-010', 2, false),
    (v_deck_id, 'ST01-011', 2, false),
    (v_deck_id, 'ST04-012', 1, false),
    (v_deck_id, 'ST04-015', 2, false);

  -- ─── deck-009: deck-009 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-009');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-009',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-009.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD01-044', 3, false),
    (v_deck_id, 'ST03-006', 3, false),
    (v_deck_id, 'GD01-093', 3, false),
    (v_deck_id, 'GD01-035', 2, false),
    (v_deck_id, 'GD01-051', 1, false),
    (v_deck_id, 'GD01-052', 2, false),
    (v_deck_id, 'GD01-111', 2, false),
    (v_deck_id, 'GD01-128', 1, false),
    (v_deck_id, 'ST03-001', 2, false),
    (v_deck_id, 'ST03-003', 1, false),
    (v_deck_id, 'ST03-008', 2, false),
    (v_deck_id, 'ST03-010', 2, false),
    (v_deck_id, 'ST03-013', 1, false);

  -- ─── deck-010: deck-010 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-010');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-010',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-010.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST05-001', 3, false),
    (v_deck_id, 'ST05-003', 3, false),
    (v_deck_id, 'ST05-010', 3, false),
    (v_deck_id, 'ST05-006', 1, false),
    (v_deck_id, 'ST05-004', 2, false),
    (v_deck_id, 'ST05-002', 1, false),
    (v_deck_id, 'ST05-005', 2, false),
    (v_deck_id, 'ST05-011', 2, false),
    (v_deck_id, 'ST05-015', 2, false),
    (v_deck_id, 'GD01-111', 2, false),
    (v_deck_id, 'GD01-060', 1, false),
    (v_deck_id, 'ST04-008', 1, false),
    (v_deck_id, 'ST05-014', 2, false),
    (v_deck_id, 'ST05-013', 1, false);

  -- ─── deck-011: deck-011 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-011');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-011',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-011.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD02-069', 3, false),
    (v_deck_id, 'GD02-097', 3, false),
    (v_deck_id, 'GD01-065', 3, false),
    (v_deck_id, 'GD02-129', 1, false),
    (v_deck_id, 'ST04-015', 1, false),
    (v_deck_id, 'ST04-012', 1, false),
    (v_deck_id, 'ST04-010', 1, false),
    (v_deck_id, 'ST04-001', 2, false),
    (v_deck_id, 'ST01-014', 1, false),
    (v_deck_id, 'GD01-118', 2, false),
    (v_deck_id, 'ST05-014', 2, false),
    (v_deck_id, 'GD02-059', 2, false),
    (v_deck_id, 'GD01-086', 1, false),
    (v_deck_id, 'GD02-079', 2, false),
    (v_deck_id, 'GD02-075', 2, false);

  -- ─── deck-012: deck-012 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-012');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-012',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-012.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD02-055', 3, false),
    (v_deck_id, 'GD02-054', 3, false),
    (v_deck_id, 'GD02-057', 3, false),
    (v_deck_id, 'GD02-058', 1, false),
    (v_deck_id, 'GD02-066', 2, false),
    (v_deck_id, 'GD02-067', 2, false),
    (v_deck_id, 'GD02-096', 2, false),
    (v_deck_id, 'GD02-110', 2, false),
    (v_deck_id, 'GD02-112', 1, false),
    (v_deck_id, 'ST05-001', 2, false),
    (v_deck_id, 'ST05-002', 1, false),
    (v_deck_id, 'ST05-010', 2, false),
    (v_deck_id, 'ST05-014', 1, false),
    (v_deck_id, 'ST05-015', 1, false);

  -- ─── deck-013: deck-013 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-013');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-013',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-013.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD02-036', 3, false),
    (v_deck_id, 'GD02-091', 3, false),
    (v_deck_id, 'GD02-107', 3, false),
    (v_deck_id, 'GD01-044', 2, false),
    (v_deck_id, 'GD01-051', 1, false),
    (v_deck_id, 'GD01-093', 2, false),
    (v_deck_id, 'ST03-001', 2, false),
    (v_deck_id, 'ST03-010', 1, false),
    (v_deck_id, 'ST03-015', 1, false),
    (v_deck_id, 'GD02-039', 1, false),
    (v_deck_id, 'GD01-035', 2, false),
    (v_deck_id, 'ST03-006', 2, false),
    (v_deck_id, 'ST03-008', 2, false);

  -- ─── deck-014: deck-014 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-014');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-014',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-014.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD02-021', 3, false),
    (v_deck_id, 'GD02-088', 3, false),
    (v_deck_id, 'GD02-002', 3, false),
    (v_deck_id, 'ST02-002', 2, false),
    (v_deck_id, 'ST02-011', 2, false),
    (v_deck_id, 'GD02-005', 1, false),
    (v_deck_id, 'ST02-006', 1, false),
    (v_deck_id, 'GD02-023', 2, false),
    (v_deck_id, 'GD02-027', 2, false),
    (v_deck_id, 'GD02-031', 1, false),
    (v_deck_id, 'GD02-035', 1, false),
    (v_deck_id, 'GD02-103', 2, false),
    (v_deck_id, 'GD02-124', 1, false),
    (v_deck_id, 'GD01-024', 2, false),
    (v_deck_id, 'GD01-100', 1, false);

  -- ─── deck-015: deck-015 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-015');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-015',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-015.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD02-001', 3, false),
    (v_deck_id, 'GD02-085', 3, false),
    (v_deck_id, 'GD01-044', 3, false),
    (v_deck_id, 'GD02-007', 1, false),
    (v_deck_id, 'GD01-051', 1, false),
    (v_deck_id, 'GD02-008', 1, false),
    (v_deck_id, 'GD02-015', 1, false),
    (v_deck_id, 'GD02-016', 2, false),
    (v_deck_id, 'GD02-013', 2, false),
    (v_deck_id, 'GD01-008', 2, false),
    (v_deck_id, 'GD02-086', 2, false),
    (v_deck_id, 'GD01-093', 2, false),
    (v_deck_id, 'ST02-014', 2, false),
    (v_deck_id, 'GD01-124', 1, false);

  -- ─── deck-016: deck-016 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-016');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-016',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-016.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST06-005', 3, false),
    (v_deck_id, 'GD02-038', 3, false),
    (v_deck_id, 'ST06-009', 3, false),
    (v_deck_id, 'GD02-041', 1, false),
    (v_deck_id, 'GD02-109', 1, false),
    (v_deck_id, 'ST06-001', 2, false),
    (v_deck_id, 'ST06-002', 1, false),
    (v_deck_id, 'ST06-006', 1, false),
    (v_deck_id, 'ST06-007', 2, false),
    (v_deck_id, 'ST06-008', 2, false),
    (v_deck_id, 'ST06-010', 2, false),
    (v_deck_id, 'ST06-014', 1, false),
    (v_deck_id, 'GD01-035', 2, false),
    (v_deck_id, 'ST03-008', 2, false);

  -- ─── deck-017: deck-017 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-017');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-017',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-017.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST07-001', 2, false),
    (v_deck_id, 'ST07-005', 3, false),
    (v_deck_id, 'GD03-049', 3, false),
    (v_deck_id, 'ST07-002', 1, false),
    (v_deck_id, 'ST07-004', 2, false),
    (v_deck_id, 'ST07-007', 2, false),
    (v_deck_id, 'ST07-009', 2, false),
    (v_deck_id, 'ST07-011', 2, false),
    (v_deck_id, 'ST07-014', 1, false),
    (v_deck_id, 'ST07-015', 1, false),
    (v_deck_id, 'GD03-026', 2, false),
    (v_deck_id, 'GD03-057', 2, false),
    (v_deck_id, 'GD03-063', 2, false);

  -- ─── deck-018: deck-018 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-018');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-018',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-018.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST08-006', 3, false),
    (v_deck_id, 'ST08-001', 3, false),
    (v_deck_id, 'ST08-002', 2, false),
    (v_deck_id, 'ST08-004', 2, false),
    (v_deck_id, 'ST08-005', 2, false),
    (v_deck_id, 'ST08-008', 2, false),
    (v_deck_id, 'ST08-009', 1, false),
    (v_deck_id, 'ST08-010', 2, false),
    (v_deck_id, 'ST08-011', 2, false),
    (v_deck_id, 'ST08-012', 1, false),
    (v_deck_id, 'ST08-013', 1, false),
    (v_deck_id, 'ST08-014', 1, false),
    (v_deck_id, 'ST08-015', 1, false),
    (v_deck_id, 'GD03-006', 1, false),
    (v_deck_id, 'GD03-036', 2, false),
    (v_deck_id, 'GD03-043', 1, false),
    (v_deck_id, 'GD03-103', 1, false);

  -- ─── deck-019: deck-019 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-019');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-019',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-019.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-017', 3, false),
    (v_deck_id, 'GD03-089', 3, false),
    (v_deck_id, 'GD03-107', 3, false),
    (v_deck_id, 'GD03-020', 2, false),
    (v_deck_id, 'GD03-024', 2, false),
    (v_deck_id, 'GD03-027', 2, false),
    (v_deck_id, 'GD03-090', 1, false),
    (v_deck_id, 'GD03-108', 2, false),
    (v_deck_id, 'GD01-030', 1, false),
    (v_deck_id, 'GD01-031', 2, false),
    (v_deck_id, 'GD01-035', 1, false),
    (v_deck_id, 'ST02-016', 1, false),
    (v_deck_id, 'ST03-008', 2, false);

  -- ─── deck-020: deck-020 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-020');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-020',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-020.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-001', 3, false),
    (v_deck_id, 'GD03-002', 3, false),
    (v_deck_id, 'GD03-084', 3, false),
    (v_deck_id, 'GD03-003', 2, false),
    (v_deck_id, 'GD03-008', 1, false),
    (v_deck_id, 'GD03-009', 1, false),
    (v_deck_id, 'GD03-012', 2, false),
    (v_deck_id, 'GD03-013', 2, false),
    (v_deck_id, 'GD03-087', 1, false),
    (v_deck_id, 'GD03-104', 1, false),
    (v_deck_id, 'GD03-123', 1, false),
    (v_deck_id, 'GD02-079', 2, false),
    (v_deck_id, 'ST01-001', 2, false),
    (v_deck_id, 'ST01-010', 2, false),
    (v_deck_id, 'ST01-014', 1, false);

  -- ─── deck-021: deck-021 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-021');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-021',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-021.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-091', 3, false),
    (v_deck_id, 'GD03-033', 3, false),
    (v_deck_id, 'GD03-127', 3, false),
    (v_deck_id, 'GD03-038', 2, false),
    (v_deck_id, 'GD03-042', 1, false),
    (v_deck_id, 'GD03-070', 2, false),
    (v_deck_id, 'GD03-118', 2, false),
    (v_deck_id, 'GD01-046', 1, false),
    (v_deck_id, 'GD01-050', 2, false),
    (v_deck_id, 'GD01-054', 1, false),
    (v_deck_id, 'GD01-066', 1, false),
    (v_deck_id, 'GD01-118', 1, false),
    (v_deck_id, 'GD01-127', 1, false),
    (v_deck_id, 'ST04-006', 2, false),
    (v_deck_id, 'ST04-008', 2, false),
    (v_deck_id, 'ST04-010', 1, false),
    (v_deck_id, 'ST04-011', 1, false);

  -- ─── deck-022: deck-022 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-022');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-022',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-022.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-002', 3, false),
    (v_deck_id, 'GD03-087', 2, false),
    (v_deck_id, 'GD03-104', 2, false),
    (v_deck_id, 'GD03-003', 2, false),
    (v_deck_id, 'GD03-004', 1, false),
    (v_deck_id, 'GD03-009', 2, false),
    (v_deck_id, 'GD02-008', 1, false),
    (v_deck_id, 'GD03-008', 2, false),
    (v_deck_id, 'GD03-012', 2, false),
    (v_deck_id, 'GD02-015', 1, false),
    (v_deck_id, 'GD03-084', 2, false),
    (v_deck_id, 'GD03-086', 1, false),
    (v_deck_id, 'GD03-118', 2, false),
    (v_deck_id, 'ST04-012', 1, false),
    (v_deck_id, 'ST01-014', 2, false),
    (v_deck_id, 'ST02-014', 2, false),
    (v_deck_id, 'GD03-123', 1, false);

  -- ─── deck-023: deck-023 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-023');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-023',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-023.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-018', 3, false),
    (v_deck_id, 'GD01-091', 3, false),
    (v_deck_id, 'ST07-005', 3, false),
    (v_deck_id, 'ST03-008', 2, false),
    (v_deck_id, 'GD01-030', 1, false),
    (v_deck_id, 'GD01-041', 1, false),
    (v_deck_id, 'GD03-026', 1, false),
    (v_deck_id, 'GD01-025', 2, false),
    (v_deck_id, 'GD01-090', 1, false),
    (v_deck_id, 'ST07-011', 1, false),
    (v_deck_id, 'GD03-117', 2, false),
    (v_deck_id, 'GD03-106', 2, false),
    (v_deck_id, 'GD03-105', 2, false),
    (v_deck_id, 'GD03-126', 2, false);

  -- ─── deck-024: deck-024 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-024');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-024',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-024.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'GD03-070', 3, false),
    (v_deck_id, 'GD03-019', 3, false),
    (v_deck_id, 'GD03-076', 3, false),
    (v_deck_id, 'GD01-081', 1, false),
    (v_deck_id, 'GD01-069', 2, false),
    (v_deck_id, 'GD03-072', 2, false),
    (v_deck_id, 'GD01-068', 1, false),
    (v_deck_id, 'GD01-065', 2, false),
    (v_deck_id, 'GD01-066', 2, false),
    (v_deck_id, 'ST04-010', 1, false),
    (v_deck_id, 'GD03-088', 1, false),
    (v_deck_id, 'GD03-118', 2, false),
    (v_deck_id, 'GD03-105', 1, false),
    (v_deck_id, 'ST01-014', 2, false),
    (v_deck_id, 'GD02-129', 1, false),
    (v_deck_id, 'ST04-015', 1, false);

  -- ─── deck-025: deck-025 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-025');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-025',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-025.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST08-001', 3, false),
    (v_deck_id, 'ST08-013', 3, false),
    (v_deck_id, 'GD02-036', 3, false),
    (v_deck_id, 'ST08-005', 1, false),
    (v_deck_id, 'GD03-056', 2, false),
    (v_deck_id, 'ST08-002', 1, false),
    (v_deck_id, 'GD03-036', 2, false),
    (v_deck_id, 'ST08-010', 2, false),
    (v_deck_id, 'GD02-091', 2, false),
    (v_deck_id, 'GD01-111', 1, false),
    (v_deck_id, 'GD02-107', 1, false),
    (v_deck_id, 'GD02-110', 1, false),
    (v_deck_id, 'ST05-014', 2, false),
    (v_deck_id, 'GD03-109', 2, false),
    (v_deck_id, 'GD03-113', 1, false),
    (v_deck_id, 'GD02-126', 1, false);

  -- ─── deck-026: deck-026 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-026');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-026',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-026.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST09-001', 4, false),
    (v_deck_id, 'ST09-002', 3, false),
    (v_deck_id, 'ST09-004', 3, false),
    (v_deck_id, 'GD01-118', 2, false),
    (v_deck_id, 'GD02-076', 1, false),
    (v_deck_id, 'GD02-110', 1, false),
    (v_deck_id, 'ST04-002', 1, false),
    (v_deck_id, 'ST04-010', 1, false),
    (v_deck_id, 'ST04-015', 2, false),
    (v_deck_id, 'ST09-005', 1, false),
    (v_deck_id, 'ST09-006', 1, false),
    (v_deck_id, 'ST09-007', 2, false),
    (v_deck_id, 'ST09-008', 2, false),
    (v_deck_id, 'ST09-010', 2, false),
    (v_deck_id, 'ST04-001', 1, false),
    (v_deck_id, 'GD01-065', 1, false),
    (v_deck_id, 'GD03-070', 1, false),
    (v_deck_id, 'GD02-058', 1, false);

  -- ─── deck-027: deck-027 ───
  v_deck_id := uuid_generate_v5(ns, base_url || 'deck-027');
  INSERT INTO public.decks (id, user_id, name, description, is_public, colors, archetype, source, source_url)
  VALUES (v_deck_id, NULL, 'deck-027',
    '',
    true, ARRAY[], ' Midrange', 'official', 'https://www.gundam-gcg.com/en/decks/deck-027.php')
  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, colors = EXCLUDED.colors, archetype = EXCLUDED.archetype, source_url = EXCLUDED.source_url;

  DELETE FROM public.deck_cards WHERE deck_id = v_deck_id;
  INSERT INTO public.deck_cards (deck_id, card_id, qty, is_boss) VALUES
    (v_deck_id, 'ST09-001', 3, false),
    (v_deck_id, 'ST09-003', 3, false),
    (v_deck_id, 'ST04-011', 3, false),
    (v_deck_id, 'GD01-049', 1, false),
    (v_deck_id, 'GD01-054', 2, false),
    (v_deck_id, 'ST04-007', 2, false),
    (v_deck_id, 'ST04-016', 1, false),
    (v_deck_id, 'ST09-002', 2, false),
    (v_deck_id, 'ST09-005', 1, false),
    (v_deck_id, 'ST09-006', 2, false),
    (v_deck_id, 'ST09-007', 1, false),
    (v_deck_id, 'ST09-008', 2, false),
    (v_deck_id, 'ST09-009', 2, false),
    (v_deck_id, 'ST09-010', 1, false),
    (v_deck_id, 'GD03-033', 1, false),
    (v_deck_id, 'GD03-091', 1, false),
    (v_deck_id, 'ST04-006', 1, false),
    (v_deck_id, 'GD01-050', 1, false);

END $$;
