/**
 * Official GCG prebuilt deck data scraped from https://www.gundam-gcg.com/en/decks/
 * Each deck includes card IDs, quantities, and boss/key cards identified from strategy text.
 *
 * Auto-generated by: npm run sync-decks
 * Last synced: 2026-03-29
 */

export interface OfficialDeckCard {
  cardId: string;
  qty: number;
  isBoss: boolean;
}

export interface OfficialDeck {
  slug: string;
  name: string;
  description: string;
  imageUrl?: string;
  archetype: string;
  colors: string[];
  sourceUrl: string;
  cards: OfficialDeckCard[];
}

export const OFFICIAL_DECKS: OfficialDeck[] = [
  // ─── deck-001 ───
  {
    slug: 'deck-001',
    name: 'deck-001',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-001.php',
    cards: [
      { cardId: 'ST01-001', qty: 3, isBoss: false },
      { cardId: 'ST04-001', qty: 3, isBoss: false },
      { cardId: 'ST01-002', qty: 1, isBoss: false },
      { cardId: 'ST01-005', qty: 2, isBoss: false },
      { cardId: 'ST04-005', qty: 2, isBoss: false },
      { cardId: 'GD01-004', qty: 1, isBoss: false },
      { cardId: 'GD01-005', qty: 1, isBoss: false },
      { cardId: 'GD01-009', qty: 1, isBoss: false },
      { cardId: 'GD01-011', qty: 1, isBoss: false },
      { cardId: 'GD01-013', qty: 1, isBoss: false },
      { cardId: 'GD01-018', qty: 2, isBoss: false },
      { cardId: 'GD01-068', qty: 1, isBoss: false },
      { cardId: 'GD01-077', qty: 1, isBoss: false },
      { cardId: 'ST01-010', qty: 2, isBoss: false },
      { cardId: 'ST04-010', qty: 2, isBoss: false },
      { cardId: 'GD01-088', qty: 1, isBoss: false },
      { cardId: 'GD01-089', qty: 1, isBoss: false },
      { cardId: 'ST01-012', qty: 1, isBoss: false },
      { cardId: 'ST01-013', qty: 1, isBoss: false },
      { cardId: 'ST04-013', qty: 1, isBoss: false },
      { cardId: 'GD01-100', qty: 2, isBoss: false },
      { cardId: 'GD01-118', qty: 1, isBoss: false },
      { cardId: 'ST01-015', qty: 2, isBoss: false },
      { cardId: 'ST04-015', qty: 1, isBoss: false },
      { cardId: 'GD01-124', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-002 ───
  {
    slug: 'deck-002',
    name: 'deck-002',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-002.php',
    cards: [
      { cardId: 'ST02-001', qty: 3, isBoss: false },
      { cardId: 'GD01-070', qty: 3, isBoss: false },
      { cardId: 'ST02-002', qty: 2, isBoss: false },
      { cardId: 'ST02-005', qty: 1, isBoss: false },
      { cardId: 'ST03-008', qty: 1, isBoss: false },
      { cardId: 'GD01-028', qty: 2, isBoss: false },
      { cardId: 'GD01-030', qty: 1, isBoss: false },
      { cardId: 'GD01-034', qty: 1, isBoss: false },
      { cardId: 'GD01-040', qty: 1, isBoss: false },
      { cardId: 'GD01-041', qty: 2, isBoss: false },
      { cardId: 'GD01-075', qty: 1, isBoss: false },
      { cardId: 'GD01-076', qty: 1, isBoss: false },
      { cardId: 'ST01-011', qty: 1, isBoss: false },
      { cardId: 'ST02-010', qty: 2, isBoss: false },
      { cardId: 'GD01-091', qty: 1, isBoss: false },
      { cardId: 'GD01-097', qty: 1, isBoss: false },
      { cardId: 'ST02-012', qty: 1, isBoss: false },
      { cardId: 'ST02-013', qty: 1, isBoss: false },
      { cardId: 'GD01-107', qty: 2, isBoss: false },
      { cardId: 'GD01-117', qty: 1, isBoss: false },
      { cardId: 'GD01-118', qty: 2, isBoss: false },
      { cardId: 'ST02-015', qty: 2, isBoss: false },
      { cardId: 'ST04-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-003 ───
  {
    slug: 'deck-003',
    name: 'deck-003',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-003.php',
    cards: [
      { cardId: 'ST01-001', qty: 3, isBoss: false },
      { cardId: 'GD01-026', qty: 3, isBoss: false },
      { cardId: 'ST01-002', qty: 2, isBoss: false },
      { cardId: 'ST01-005', qty: 2, isBoss: false },
      { cardId: 'ST02-001', qty: 2, isBoss: false },
      { cardId: 'ST02-005', qty: 1, isBoss: false },
      { cardId: 'ST03-007', qty: 1, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
      { cardId: 'GD01-004', qty: 1, isBoss: false },
      { cardId: 'GD01-015', qty: 1, isBoss: false },
      { cardId: 'GD01-016', qty: 1, isBoss: false },
      { cardId: 'GD01-030', qty: 1, isBoss: false },
      { cardId: 'GD01-031', qty: 1, isBoss: false },
      { cardId: 'GD01-040', qty: 1, isBoss: false },
      { cardId: 'ST01-010', qty: 2, isBoss: false },
      { cardId: 'ST03-011', qty: 2, isBoss: false },
      { cardId: 'ST02-010', qty: 2, isBoss: false },
      { cardId: 'GD01-105', qty: 1, isBoss: false },
      { cardId: 'ST01-013', qty: 1, isBoss: false },
      { cardId: 'GD01-100', qty: 2, isBoss: false },
      { cardId: 'GD01-099', qty: 1, isBoss: false },
      { cardId: 'ST03-016', qty: 1, isBoss: false },
      { cardId: 'ST01-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-004 ───
  {
    slug: 'deck-004',
    name: 'deck-004',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-004.php',
    cards: [
      { cardId: 'ST01-010', qty: 3, isBoss: false },
      { cardId: 'ST01-011', qty: 3, isBoss: false },
      { cardId: 'ST01-014', qty: 3, isBoss: false },
      { cardId: 'ST01-001', qty: 2, isBoss: false },
      { cardId: 'ST01-002', qty: 1, isBoss: false },
      { cardId: 'ST01-003', qty: 1, isBoss: false },
      { cardId: 'ST01-004', qty: 2, isBoss: false },
      { cardId: 'ST01-005', qty: 2, isBoss: false },
      { cardId: 'ST01-006', qty: 2, isBoss: false },
      { cardId: 'ST01-007', qty: 1, isBoss: false },
      { cardId: 'ST01-009', qty: 2, isBoss: false },
      { cardId: 'ST01-012', qty: 1, isBoss: false },
      { cardId: 'ST01-015', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-005 ───
  {
    slug: 'deck-005',
    name: 'deck-005',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-005.php',
    cards: [
      { cardId: 'ST02-001', qty: 3, isBoss: false },
      { cardId: 'ST02-002', qty: 4, isBoss: false },
      { cardId: 'ST02-006', qty: 3, isBoss: false },
      { cardId: 'ST02-003', qty: 1, isBoss: false },
      { cardId: 'ST02-005', qty: 1, isBoss: false },
      { cardId: 'ST02-008', qty: 2, isBoss: false },
      { cardId: 'ST02-009', qty: 2, isBoss: false },
      { cardId: 'ST02-010', qty: 2, isBoss: false },
      { cardId: 'ST02-011', qty: 2, isBoss: false },
      { cardId: 'ST02-012', qty: 1, isBoss: false },
      { cardId: 'ST02-014', qty: 2, isBoss: false },
      { cardId: 'ST02-016', qty: 1, isBoss: false },
      { cardId: 'ST02-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-006 ───
  {
    slug: 'deck-006',
    name: 'deck-006',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-006.php',
    cards: [
      { cardId: 'ST03-001', qty: 3, isBoss: false },
      { cardId: 'ST03-006', qty: 3, isBoss: false },
      { cardId: 'ST03-013', qty: 3, isBoss: false },
      { cardId: 'ST03-002', qty: 1, isBoss: false },
      { cardId: 'ST03-003', qty: 1, isBoss: false },
      { cardId: 'ST03-004', qty: 2, isBoss: false },
      { cardId: 'ST03-007', qty: 2, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
      { cardId: 'ST03-009', qty: 2, isBoss: false },
      { cardId: 'ST03-010', qty: 2, isBoss: false },
      { cardId: 'ST03-011', qty: 1, isBoss: false },
      { cardId: 'ST03-014', qty: 1, isBoss: false },
      { cardId: 'ST03-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-007 ───
  {
    slug: 'deck-007',
    name: 'deck-007',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-007.php',
    cards: [
      { cardId: 'ST04-006', qty: 3, isBoss: false },
      { cardId: 'ST04-001', qty: 3, isBoss: false },
      { cardId: 'ST04-012', qty: 3, isBoss: false },
      { cardId: 'ST04-002', qty: 2, isBoss: false },
      { cardId: 'ST04-003', qty: 1, isBoss: false },
      { cardId: 'ST04-004', qty: 1, isBoss: false },
      { cardId: 'ST04-005', qty: 2, isBoss: false },
      { cardId: 'ST04-007', qty: 2, isBoss: false },
      { cardId: 'ST04-008', qty: 1, isBoss: false },
      { cardId: 'ST04-010', qty: 1, isBoss: false },
      { cardId: 'ST04-011', qty: 2, isBoss: false },
      { cardId: 'ST04-013', qty: 2, isBoss: false },
      { cardId: 'ST04-015', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-008 ───
  {
    slug: 'deck-008',
    name: 'deck-008',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-008.php',
    cards: [
      { cardId: 'ST04-001', qty: 3, isBoss: false },
      { cardId: 'ST04-002', qty: 1, isBoss: false },
      { cardId: 'ST04-010', qty: 2, isBoss: false },
      { cardId: 'GD01-004', qty: 2, isBoss: false },
      { cardId: 'GD01-065', qty: 2, isBoss: false },
      { cardId: 'GD01-066', qty: 2, isBoss: false },
      { cardId: 'GD01-067', qty: 2, isBoss: false },
      { cardId: 'GD01-086', qty: 1, isBoss: false },
      { cardId: 'GD01-100', qty: 1, isBoss: false },
      { cardId: 'GD01-118', qty: 1, isBoss: false },
      { cardId: 'ST01-009', qty: 2, isBoss: false },
      { cardId: 'ST01-010', qty: 2, isBoss: false },
      { cardId: 'ST01-011', qty: 2, isBoss: false },
      { cardId: 'ST04-012', qty: 1, isBoss: false },
      { cardId: 'ST04-015', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-009 ───
  {
    slug: 'deck-009',
    name: 'deck-009',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-009.php',
    cards: [
      { cardId: 'GD01-044', qty: 3, isBoss: false },
      { cardId: 'ST03-006', qty: 3, isBoss: false },
      { cardId: 'GD01-093', qty: 3, isBoss: false },
      { cardId: 'GD01-035', qty: 2, isBoss: false },
      { cardId: 'GD01-051', qty: 1, isBoss: false },
      { cardId: 'GD01-052', qty: 2, isBoss: false },
      { cardId: 'GD01-111', qty: 2, isBoss: false },
      { cardId: 'GD01-128', qty: 1, isBoss: false },
      { cardId: 'ST03-001', qty: 2, isBoss: false },
      { cardId: 'ST03-003', qty: 1, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
      { cardId: 'ST03-010', qty: 2, isBoss: false },
      { cardId: 'ST03-013', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-010 ───
  {
    slug: 'deck-010',
    name: 'deck-010',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-010.php',
    cards: [
      { cardId: 'ST05-001', qty: 3, isBoss: false },
      { cardId: 'ST05-003', qty: 3, isBoss: false },
      { cardId: 'ST05-010', qty: 3, isBoss: false },
      { cardId: 'ST05-006', qty: 1, isBoss: false },
      { cardId: 'ST05-004', qty: 2, isBoss: false },
      { cardId: 'ST05-002', qty: 1, isBoss: false },
      { cardId: 'ST05-005', qty: 2, isBoss: false },
      { cardId: 'ST05-011', qty: 2, isBoss: false },
      { cardId: 'ST05-015', qty: 2, isBoss: false },
      { cardId: 'GD01-111', qty: 2, isBoss: false },
      { cardId: 'GD01-060', qty: 1, isBoss: false },
      { cardId: 'ST04-008', qty: 1, isBoss: false },
      { cardId: 'ST05-014', qty: 2, isBoss: false },
      { cardId: 'ST05-013', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-011 ───
  {
    slug: 'deck-011',
    name: 'deck-011',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-011.php',
    cards: [
      { cardId: 'GD02-069', qty: 3, isBoss: false },
      { cardId: 'GD02-097', qty: 3, isBoss: false },
      { cardId: 'GD01-065', qty: 3, isBoss: false },
      { cardId: 'GD02-129', qty: 1, isBoss: false },
      { cardId: 'ST04-015', qty: 1, isBoss: false },
      { cardId: 'ST04-012', qty: 1, isBoss: false },
      { cardId: 'ST04-010', qty: 1, isBoss: false },
      { cardId: 'ST04-001', qty: 2, isBoss: false },
      { cardId: 'ST01-014', qty: 1, isBoss: false },
      { cardId: 'GD01-118', qty: 2, isBoss: false },
      { cardId: 'ST05-014', qty: 2, isBoss: false },
      { cardId: 'GD02-059', qty: 2, isBoss: false },
      { cardId: 'GD01-086', qty: 1, isBoss: false },
      { cardId: 'GD02-079', qty: 2, isBoss: false },
      { cardId: 'GD02-075', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-012 ───
  {
    slug: 'deck-012',
    name: 'deck-012',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-012.php',
    cards: [
      { cardId: 'GD02-055', qty: 3, isBoss: false },
      { cardId: 'GD02-054', qty: 3, isBoss: false },
      { cardId: 'GD02-057', qty: 3, isBoss: false },
      { cardId: 'GD02-058', qty: 1, isBoss: false },
      { cardId: 'GD02-066', qty: 2, isBoss: false },
      { cardId: 'GD02-067', qty: 2, isBoss: false },
      { cardId: 'GD02-096', qty: 2, isBoss: false },
      { cardId: 'GD02-110', qty: 2, isBoss: false },
      { cardId: 'GD02-112', qty: 1, isBoss: false },
      { cardId: 'ST05-001', qty: 2, isBoss: false },
      { cardId: 'ST05-002', qty: 1, isBoss: false },
      { cardId: 'ST05-010', qty: 2, isBoss: false },
      { cardId: 'ST05-014', qty: 1, isBoss: false },
      { cardId: 'ST05-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-013 ───
  {
    slug: 'deck-013',
    name: 'deck-013',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-013.php',
    cards: [
      { cardId: 'GD02-036', qty: 3, isBoss: false },
      { cardId: 'GD02-091', qty: 3, isBoss: false },
      { cardId: 'GD02-107', qty: 3, isBoss: false },
      { cardId: 'GD01-044', qty: 2, isBoss: false },
      { cardId: 'GD01-051', qty: 1, isBoss: false },
      { cardId: 'GD01-093', qty: 2, isBoss: false },
      { cardId: 'ST03-001', qty: 2, isBoss: false },
      { cardId: 'ST03-010', qty: 1, isBoss: false },
      { cardId: 'ST03-015', qty: 1, isBoss: false },
      { cardId: 'GD02-039', qty: 1, isBoss: false },
      { cardId: 'GD01-035', qty: 2, isBoss: false },
      { cardId: 'ST03-006', qty: 2, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-014 ───
  {
    slug: 'deck-014',
    name: 'deck-014',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-014.php',
    cards: [
      { cardId: 'GD02-021', qty: 3, isBoss: false },
      { cardId: 'GD02-088', qty: 3, isBoss: false },
      { cardId: 'GD02-002', qty: 3, isBoss: false },
      { cardId: 'ST02-002', qty: 2, isBoss: false },
      { cardId: 'ST02-011', qty: 2, isBoss: false },
      { cardId: 'GD02-005', qty: 1, isBoss: false },
      { cardId: 'ST02-006', qty: 1, isBoss: false },
      { cardId: 'GD02-023', qty: 2, isBoss: false },
      { cardId: 'GD02-027', qty: 2, isBoss: false },
      { cardId: 'GD02-031', qty: 1, isBoss: false },
      { cardId: 'GD02-035', qty: 1, isBoss: false },
      { cardId: 'GD02-103', qty: 2, isBoss: false },
      { cardId: 'GD02-124', qty: 1, isBoss: false },
      { cardId: 'GD01-024', qty: 2, isBoss: false },
      { cardId: 'GD01-100', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-015 ───
  {
    slug: 'deck-015',
    name: 'deck-015',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-015.php',
    cards: [
      { cardId: 'GD02-001', qty: 3, isBoss: false },
      { cardId: 'GD02-085', qty: 3, isBoss: false },
      { cardId: 'GD01-044', qty: 3, isBoss: false },
      { cardId: 'GD02-007', qty: 1, isBoss: false },
      { cardId: 'GD01-051', qty: 1, isBoss: false },
      { cardId: 'GD02-008', qty: 1, isBoss: false },
      { cardId: 'GD02-015', qty: 1, isBoss: false },
      { cardId: 'GD02-016', qty: 2, isBoss: false },
      { cardId: 'GD02-013', qty: 2, isBoss: false },
      { cardId: 'GD01-008', qty: 2, isBoss: false },
      { cardId: 'GD02-086', qty: 2, isBoss: false },
      { cardId: 'GD01-093', qty: 2, isBoss: false },
      { cardId: 'ST02-014', qty: 2, isBoss: false },
      { cardId: 'GD01-124', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-016 ───
  {
    slug: 'deck-016',
    name: 'deck-016',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-016.php',
    cards: [
      { cardId: 'ST06-005', qty: 3, isBoss: false },
      { cardId: 'GD02-038', qty: 3, isBoss: false },
      { cardId: 'ST06-009', qty: 3, isBoss: false },
      { cardId: 'GD02-041', qty: 1, isBoss: false },
      { cardId: 'GD02-109', qty: 1, isBoss: false },
      { cardId: 'ST06-001', qty: 2, isBoss: false },
      { cardId: 'ST06-002', qty: 1, isBoss: false },
      { cardId: 'ST06-006', qty: 1, isBoss: false },
      { cardId: 'ST06-007', qty: 2, isBoss: false },
      { cardId: 'ST06-008', qty: 2, isBoss: false },
      { cardId: 'ST06-010', qty: 2, isBoss: false },
      { cardId: 'ST06-014', qty: 1, isBoss: false },
      { cardId: 'GD01-035', qty: 2, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-017 ───
  {
    slug: 'deck-017',
    name: 'deck-017',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-017.php',
    cards: [
      { cardId: 'ST07-001', qty: 2, isBoss: false },
      { cardId: 'ST07-005', qty: 3, isBoss: false },
      { cardId: 'GD03-049', qty: 3, isBoss: false },
      { cardId: 'ST07-002', qty: 1, isBoss: false },
      { cardId: 'ST07-004', qty: 2, isBoss: false },
      { cardId: 'ST07-007', qty: 2, isBoss: false },
      { cardId: 'ST07-009', qty: 2, isBoss: false },
      { cardId: 'ST07-011', qty: 2, isBoss: false },
      { cardId: 'ST07-014', qty: 1, isBoss: false },
      { cardId: 'ST07-015', qty: 1, isBoss: false },
      { cardId: 'GD03-026', qty: 2, isBoss: false },
      { cardId: 'GD03-057', qty: 2, isBoss: false },
      { cardId: 'GD03-063', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-018 ───
  {
    slug: 'deck-018',
    name: 'deck-018',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-018.php',
    cards: [
      { cardId: 'ST08-006', qty: 3, isBoss: false },
      { cardId: 'ST08-001', qty: 3, isBoss: false },
      { cardId: 'ST08-002', qty: 2, isBoss: false },
      { cardId: 'ST08-004', qty: 2, isBoss: false },
      { cardId: 'ST08-005', qty: 2, isBoss: false },
      { cardId: 'ST08-008', qty: 2, isBoss: false },
      { cardId: 'ST08-009', qty: 1, isBoss: false },
      { cardId: 'ST08-010', qty: 2, isBoss: false },
      { cardId: 'ST08-011', qty: 2, isBoss: false },
      { cardId: 'ST08-012', qty: 1, isBoss: false },
      { cardId: 'ST08-013', qty: 1, isBoss: false },
      { cardId: 'ST08-014', qty: 1, isBoss: false },
      { cardId: 'ST08-015', qty: 1, isBoss: false },
      { cardId: 'GD03-006', qty: 1, isBoss: false },
      { cardId: 'GD03-036', qty: 2, isBoss: false },
      { cardId: 'GD03-043', qty: 1, isBoss: false },
      { cardId: 'GD03-103', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-019 ───
  {
    slug: 'deck-019',
    name: 'deck-019',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-019.php',
    cards: [
      { cardId: 'GD03-017', qty: 3, isBoss: false },
      { cardId: 'GD03-089', qty: 3, isBoss: false },
      { cardId: 'GD03-107', qty: 3, isBoss: false },
      { cardId: 'GD03-020', qty: 2, isBoss: false },
      { cardId: 'GD03-024', qty: 2, isBoss: false },
      { cardId: 'GD03-027', qty: 2, isBoss: false },
      { cardId: 'GD03-090', qty: 1, isBoss: false },
      { cardId: 'GD03-108', qty: 2, isBoss: false },
      { cardId: 'GD01-030', qty: 1, isBoss: false },
      { cardId: 'GD01-031', qty: 2, isBoss: false },
      { cardId: 'GD01-035', qty: 1, isBoss: false },
      { cardId: 'ST02-016', qty: 1, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-020 ───
  {
    slug: 'deck-020',
    name: 'deck-020',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-020.php',
    cards: [
      { cardId: 'GD03-001', qty: 3, isBoss: false },
      { cardId: 'GD03-002', qty: 3, isBoss: false },
      { cardId: 'GD03-084', qty: 3, isBoss: false },
      { cardId: 'GD03-003', qty: 2, isBoss: false },
      { cardId: 'GD03-008', qty: 1, isBoss: false },
      { cardId: 'GD03-009', qty: 1, isBoss: false },
      { cardId: 'GD03-012', qty: 2, isBoss: false },
      { cardId: 'GD03-013', qty: 2, isBoss: false },
      { cardId: 'GD03-087', qty: 1, isBoss: false },
      { cardId: 'GD03-104', qty: 1, isBoss: false },
      { cardId: 'GD03-123', qty: 1, isBoss: false },
      { cardId: 'GD02-079', qty: 2, isBoss: false },
      { cardId: 'ST01-001', qty: 2, isBoss: false },
      { cardId: 'ST01-010', qty: 2, isBoss: false },
      { cardId: 'ST01-014', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-021 ───
  {
    slug: 'deck-021',
    name: 'deck-021',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-021.php',
    cards: [
      { cardId: 'GD03-091', qty: 3, isBoss: false },
      { cardId: 'GD03-033', qty: 3, isBoss: false },
      { cardId: 'GD03-127', qty: 3, isBoss: false },
      { cardId: 'GD03-038', qty: 2, isBoss: false },
      { cardId: 'GD03-042', qty: 1, isBoss: false },
      { cardId: 'GD03-070', qty: 2, isBoss: false },
      { cardId: 'GD03-118', qty: 2, isBoss: false },
      { cardId: 'GD01-046', qty: 1, isBoss: false },
      { cardId: 'GD01-050', qty: 2, isBoss: false },
      { cardId: 'GD01-054', qty: 1, isBoss: false },
      { cardId: 'GD01-066', qty: 1, isBoss: false },
      { cardId: 'GD01-118', qty: 1, isBoss: false },
      { cardId: 'GD01-127', qty: 1, isBoss: false },
      { cardId: 'ST04-006', qty: 2, isBoss: false },
      { cardId: 'ST04-008', qty: 2, isBoss: false },
      { cardId: 'ST04-010', qty: 1, isBoss: false },
      { cardId: 'ST04-011', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-022 ───
  {
    slug: 'deck-022',
    name: 'deck-022',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-022.php',
    cards: [
      { cardId: 'GD03-002', qty: 3, isBoss: false },
      { cardId: 'GD03-087', qty: 2, isBoss: false },
      { cardId: 'GD03-104', qty: 2, isBoss: false },
      { cardId: 'GD03-003', qty: 2, isBoss: false },
      { cardId: 'GD03-004', qty: 1, isBoss: false },
      { cardId: 'GD03-009', qty: 2, isBoss: false },
      { cardId: 'GD02-008', qty: 1, isBoss: false },
      { cardId: 'GD03-008', qty: 2, isBoss: false },
      { cardId: 'GD03-012', qty: 2, isBoss: false },
      { cardId: 'GD02-015', qty: 1, isBoss: false },
      { cardId: 'GD03-084', qty: 2, isBoss: false },
      { cardId: 'GD03-086', qty: 1, isBoss: false },
      { cardId: 'GD03-118', qty: 2, isBoss: false },
      { cardId: 'ST04-012', qty: 1, isBoss: false },
      { cardId: 'ST01-014', qty: 2, isBoss: false },
      { cardId: 'ST02-014', qty: 2, isBoss: false },
      { cardId: 'GD03-123', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-023 ───
  {
    slug: 'deck-023',
    name: 'deck-023',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-023.php',
    cards: [
      { cardId: 'GD03-018', qty: 3, isBoss: false },
      { cardId: 'GD01-091', qty: 3, isBoss: false },
      { cardId: 'ST07-005', qty: 3, isBoss: false },
      { cardId: 'ST03-008', qty: 2, isBoss: false },
      { cardId: 'GD01-030', qty: 1, isBoss: false },
      { cardId: 'GD01-041', qty: 1, isBoss: false },
      { cardId: 'GD03-026', qty: 1, isBoss: false },
      { cardId: 'GD01-025', qty: 2, isBoss: false },
      { cardId: 'GD01-090', qty: 1, isBoss: false },
      { cardId: 'ST07-011', qty: 1, isBoss: false },
      { cardId: 'GD03-117', qty: 2, isBoss: false },
      { cardId: 'GD03-106', qty: 2, isBoss: false },
      { cardId: 'GD03-105', qty: 2, isBoss: false },
      { cardId: 'GD03-126', qty: 2, isBoss: false },
    ],
  },

  // ─── deck-024 ───
  {
    slug: 'deck-024',
    name: 'deck-024',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-024.php',
    cards: [
      { cardId: 'GD03-070', qty: 3, isBoss: false },
      { cardId: 'GD03-019', qty: 3, isBoss: false },
      { cardId: 'GD03-076', qty: 3, isBoss: false },
      { cardId: 'GD01-081', qty: 1, isBoss: false },
      { cardId: 'GD01-069', qty: 2, isBoss: false },
      { cardId: 'GD03-072', qty: 2, isBoss: false },
      { cardId: 'GD01-068', qty: 1, isBoss: false },
      { cardId: 'GD01-065', qty: 2, isBoss: false },
      { cardId: 'GD01-066', qty: 2, isBoss: false },
      { cardId: 'ST04-010', qty: 1, isBoss: false },
      { cardId: 'GD03-088', qty: 1, isBoss: false },
      { cardId: 'GD03-118', qty: 2, isBoss: false },
      { cardId: 'GD03-105', qty: 1, isBoss: false },
      { cardId: 'ST01-014', qty: 2, isBoss: false },
      { cardId: 'GD02-129', qty: 1, isBoss: false },
      { cardId: 'ST04-015', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-025 ───
  {
    slug: 'deck-025',
    name: 'deck-025',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-025.php',
    cards: [
      { cardId: 'ST08-001', qty: 3, isBoss: false },
      { cardId: 'ST08-013', qty: 3, isBoss: false },
      { cardId: 'GD02-036', qty: 3, isBoss: false },
      { cardId: 'ST08-005', qty: 1, isBoss: false },
      { cardId: 'GD03-056', qty: 2, isBoss: false },
      { cardId: 'ST08-002', qty: 1, isBoss: false },
      { cardId: 'GD03-036', qty: 2, isBoss: false },
      { cardId: 'ST08-010', qty: 2, isBoss: false },
      { cardId: 'GD02-091', qty: 2, isBoss: false },
      { cardId: 'GD01-111', qty: 1, isBoss: false },
      { cardId: 'GD02-107', qty: 1, isBoss: false },
      { cardId: 'GD02-110', qty: 1, isBoss: false },
      { cardId: 'ST05-014', qty: 2, isBoss: false },
      { cardId: 'GD03-109', qty: 2, isBoss: false },
      { cardId: 'GD03-113', qty: 1, isBoss: false },
      { cardId: 'GD02-126', qty: 1, isBoss: false },
    ],
  },

  // ─── deck-026 ───
  {
    slug: 'deck-026',
    name: 'deck-026',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-026.php',
    cards: [
      { cardId: 'ST09-001', qty: 4, isBoss: false },
      { cardId: 'ST09-002', qty: 4, isBoss: false },
      { cardId: 'ST09-004', qty: 4, isBoss: false },
      { cardId: 'GD01-118', qty: 4, isBoss: false },
      { cardId: 'GD02-076', qty: 2, isBoss: false },
      { cardId: 'GD02-110', qty: 3, isBoss: false },
      { cardId: 'ST04-002', qty: 3, isBoss: false },
      { cardId: 'ST04-010', qty: 4, isBoss: false },
      { cardId: 'ST04-015', qty: 2, isBoss: false },
      { cardId: 'ST09-005', qty: 4, isBoss: false },
      { cardId: 'ST09-006', qty: 4, isBoss: false },
      { cardId: 'ST09-007', qty: 4, isBoss: false },
      { cardId: 'ST09-008', qty: 4, isBoss: false },
      { cardId: 'ST09-010', qty: 4, isBoss: false },
    ],
  },

  // ─── deck-027 ───
  {
    slug: 'deck-027',
    name: 'deck-027',
    description:
      '',
    archetype: ' Midrange',
    colors: [],
    sourceUrl: 'https://www.gundam-gcg.com/en/decks/deck-027.php',
    cards: [
      { cardId: 'ST09-001', qty: 4, isBoss: false },
      { cardId: 'ST09-003', qty: 4, isBoss: false },
      { cardId: 'ST04-011', qty: 4, isBoss: false },
      { cardId: 'GD01-049', qty: 3, isBoss: false },
      { cardId: 'GD01-054', qty: 4, isBoss: false },
      { cardId: 'ST04-007', qty: 4, isBoss: false },
      { cardId: 'ST04-016', qty: 2, isBoss: false },
      { cardId: 'ST09-002', qty: 4, isBoss: false },
      { cardId: 'ST09-005', qty: 4, isBoss: false },
      { cardId: 'ST09-006', qty: 4, isBoss: false },
      { cardId: 'ST09-007', qty: 4, isBoss: false },
      { cardId: 'ST09-008', qty: 4, isBoss: false },
      { cardId: 'ST09-009', qty: 2, isBoss: false },
      { cardId: 'ST09-010', qty: 3, isBoss: false },
    ],
  },

];
